### ISSUE TITLE
micro_geo2kml.py errors when run 

### ISSUE THREAD

**Issue by hazemsamoaa** [bonzanini/Book-SocialMediaMiningPython#13]
Hi, 
while executing the python file micro_geo2kml.py I found many errors 
first for loop in the line 39, can't accept the argument. 
in the line 40 for the same reson 
![image](https://user-images.githubusercontent.com/37386593/50932279-64fc0080-1465-11e9-83ea-dd46990a618c.png)

**Comment by bonzanini** [comment]
Thank you, a type conversion was missing, now the `--n` argument is converted to `int` as it should be
