### ISSUE TITLE
stream example file .raise ConnectionError(err, request=request)

### ISSUE THREAD

**Issue by Nasr-Z1** [bonzanini/Book-SocialMediaMiningPython#3]
hello @bonzanini  first of all , thanks for your great book , its really really useful book ,
i have many question but for now it will be in the twitter stream example , plz forgive me if any of them seem naive , 
when i use stream example , give me the error above ,
here 's a photo
![stream2](https://cloud.githubusercontent.com/assets/11332435/26009699/42c80576-374a-11e7-83c0-787bb39ce53b.PNG)
am using python 3 by the way
and by the way , what is 'rugby' for ,  i thought its because of the name of file , but it was only part of the file name , in the book said its a key word , but i couldn't understand it-why keyword with hashtag'? , thanks any way

**Comment by bonzanini** [comment]
@Nasr-Z1 I see you're closing the issue, was the problem solved? It looks like a network problem

The word rugby was one of the search keyword in the book example, and it was used as a regular term in conjunction with hashtags. This was just to showcase that you can use both regular keywords and hashtags in the same search.

**Comment by Nasr-Z1** [comment]
yeah it was a network problem 👍 
and thanks now i understand , very useful script indeed .
