### ISSUE TITLE
twitter_get_user_timeline code example , encode problem with Araic tweets 

### ISSUE THREAD

**Issue by Nasr-Z1** [bonzanini/Book-SocialMediaMiningPython#4]
hello sir @bonzanini , in all of your scripts , when i deal with arabic tweets i get it encoded, for example, twitter_get_user_timeline to get an arabin user tweets , all arab words , in any entity include ,text or user name , etc .. , 
encoded like this : \u0627\u0644\u0646\u0627\u0633 \u062f\u064a \u0639\u0627\u064a\u0634\u0647 \u0644\u064a\u0647 
help me plz thank you in advance its by the way in the most of all the scripts .thanks for all your great work ,
am using python 3 by the way .

**Comment by bonzanini** [comment]
@Nasr-Z1 yes that's how the text is going to be displayed on file, but if you print it out you should see the Arabic characters being displayed correctly

**Comment by Nasr-Z1** [comment]
ok thank you very much @bonzanini  , can you help me with the code to access all fields like text or any field in the file ,
thanks any way ^^
