### ISSUE TITLE
twitter_time_series.py error when run 

### ISSUE THREAD

**Issue by alphagamer7** [bonzanini/Book-SocialMediaMiningPython#6]
Using Windows 10 , python 3.5.3 
Chapter 2-3.
When I run the twitter_time_series.py (with the following argument -python twitter_time_series.py stream__RWC2015__RWCFinal_Rugby.jsonl ) I am getting the following error
![image](https://user-images.githubusercontent.com/17358908/27764974-ff7c71e8-5ec3-11e7-8f79-2e2282407898.png)
Why is the jsonl file not read?

**Comment by bonzanini** [comment]
How did you create the .jsonl file and is it in the correct JSON Lines format? e.g. one tweet per line, no empty lines

**Comment by alphagamer7** [comment]
Fixed issue.The issue was that the .jsonl file created had empty line when it was created.
