### ISSUE TITLE
twitter_get_user_timeline.py

### ISSUE THREAD

**Issue by christophjones** [bonzanini/Book-SocialMediaMiningPython#9]
I'm able to run get_home_timeline.py but user_timeline erros with the following.  Any guidance is appreciated.

runfile('C:/Users/chris/Documents/DataMiningWithPython/Book-SocialMediaMiningPython-master/Chap02-03/twitter_get_user_timeline.py', wdir='C:/Users/chris/Documents/DataMiningWithPython/Book-SocialMediaMiningPython-master/Chap02-03')
Reloaded modules: twitter_client
sys argv:  ['C:/Users/chris/Documents/DataMiningWithPython/Book-SocialMediaMiningPython-master/Chap02-03/twitter_get_user_timeline.py']
Usage:
python C:/Users/chris/Documents/DataMiningWithPython/Book-SocialMediaMiningPython-master/Chap02-03/twitter_get_user_timeline.py <username>
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

C:\Users\chris\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by bonzanini** [comment]
How do you run the script?

When you run from the command line, the script expects the twitter username as first argument, e.g.

`python twitter_get_user_timeline.py marcobonzanini`

**Comment by christophjones** [comment]
That's the problem, I was running it from the script editor in Spyder and
not entering the username.  It works when I run it from command line.  I
need to find a way to enter the argument in editor.  Thanks

**Comment by bonzanini** [comment]
Using the menu `Run -> Configuration per file` (or `Run -> Configure` depending on the version of your editor), you can specify the command line options.

Hope this helps

**Comment by christophjones** [comment]
perfect.  thanks again
